### PR TITLE
ysong

### PR DESCRIPTION
**Pull request by YY-SONG0718**
Add file ysong.txt

### CODE REVIEW

**Comment by YY-SONG0718** [comment]
Related to issue #11

**Comment by YY-SONG0718** [comment]
Related to issue 11

**Comment by helrick** [comment]
just FYI, it's not super intuitive, but you need to use the "#" sign to link to the issue 😊

i.e. Related to issue #11

**Comment by YY-SONG0718** [comment]
> just FYI, it's not super intuitive, but you need to use the "#" sign to link to the issue 😊
> 
> i.e. Related to issue #11

Thank you Hillary! Couldn't find the hashtag on the VM but I am sure will do so in the future :)

**Pull request merged**
